import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ransara Radio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="google-site-verification" content="98kAUw7yYmVhILpIbwDU-FhFrqyO8-oYbQargdjE4EA" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Welcome to Ransara Radio
        </h3>

        <div className={styles.grid}>
          <iframe src="https://video1.getstreamhosting.com:2000/AudioPlayer/8396?showSettingsLink=true&mount=&" width="100%" style={{width: "100%"}} border="0" height="200px"></iframe>
          <iframe src="https://video1.getstreamhosting.com:2000/map/8396" width="100%" height="300px" border="0" allowtransparency="true"></iframe>
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Sandun with Love
        </a>
      </footer>
    </div>
  )
}
